Fix compilation on arm32
This should fix https://github.com/containers/gvisor-tap-vsock/issues/545
MaxInt32 should be strictly smaller than MaxUint32 and thus fit both in
an int32 and an uint32.

This fixes this compilation error:
```
pkg/tap/protocols.go:56:12: math.MaxUint32 (untyped int constant 4294967295) overflows int
```

Signed-off-by: Christophe Fergeau <cfergeau@redhat.com>